version: '3.4'
services:
  crowd:
    image: zouchengli/crowd
    container_name: crowd-srv
    environment:
      - TZ='Asia/Shanghai'
#      - JVM_MINIMUM_MEMORY=1g
#      - JVM_MAXIMUM_MEMORY=12g
#      - JVM_CODE_CACHE_ARGS='-XX:InitialCodeCacheSize=1g -XX:ReservedCodeCacheSize=8g'
    depends_on:
      - mysql
    ports:
      - "8095:8095"
    volumes:
      - home_data:/var/crowd
    restart: always
    networks:
      - network-bridge

  mysql:
    image: mysql:5.7
    container_name: mysql-crowd
    environment:
      - TZ='Asia/Shanghai'
      - MYSQL_DATABASE=crowd
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=crowd
      - MYSQL_PASSWORD=123123
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin']
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  home_data:
    external: false
  mysql_data:
    external: false